In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [2]:
train_df = pd.read_csv('../Datasets/Boston/processed_train.csv')

In [3]:
train_df.head()

Id  MSSubClass  LotArea  OverallQual  OverallCond  YearBuilt  YearRemodAdd  \
0   1          60     8450            7            5       2003          2003   
1   2          20     9600            6            8       1976          1976   
2   3          60    11250            7            5       2001          2002   
3   4          70     9550            7            5       1915          1970   
4   5          60    14260            8            5       2000          2000   

   BsmtFinSF1  BsmtFinSF2  BsmtUnfSF  ...  SaleType_ConLw  SaleType_New  \
0         706           0        150  ...               0             0   
1         978           0        284  ...               0             0   
2         486           0        434  ...               0             0   
3         216           0        540  ...               0             0   
4         655           0        490  ...               0             0   

   SaleType_Oth  SaleType_WD  SaleCondition_Abnorml  SaleCondition_AdjLand  \
0             0            1                      0                      0   
1             0            1                      0                      0   
2             0            1                      0                      0   
3             0            1                      1                      0   
4             0            1                      0                      0   

   SaleCondition_Alloca  SaleCondition_Family  SaleCondition_Normal  \
0                     0                     0                     1   
1                     0                     0                     1   
2                     0                     0                     1   
3                     0                     0                     0   
4                     0                     0                     1   

   SaleCondition_Partial  
0                      0  
1                      0  
2                      0  
3                      0  
4                      0  

[5 rows x 222 columns]

In [4]:
train_df.SalePrice

0       12.247694
1       12.109011
2       12.317167
3       11.849398
4       12.429216
          ...    
1452    12.072541
1453    12.254863
1454    12.493130
1455    11.864462
1456    11.901583
Name: SalePrice, Length: 1457, dtype: float64

In [5]:
Features = train_df.loc[:,train_df.columns != 'SalePrice']

In [6]:
labels =  train_df.loc[:,'SalePrice']

In [7]:
Features

Id  MSSubClass  LotArea  OverallQual  OverallCond  YearBuilt  \
0        1          60     8450            7            5       2003   
1        2          20     9600            6            8       1976   
2        3          60    11250            7            5       2001   
3        4          70     9550            7            5       1915   
4        5          60    14260            8            5       2000   
...    ...         ...      ...          ...          ...        ...   
1452  1456          60     7917            6            5       1999   
1453  1457          20    13175            6            6       1978   
1454  1458          70     9042            7            9       1941   
1455  1459          20     9717            5            6       1950   
1456  1460          20     9937            5            6       1965   

      YearRemodAdd  BsmtFinSF1  BsmtFinSF2  BsmtUnfSF  ...  SaleType_ConLw  \
0             2003         706           0        150  ...               0   
1             1976         978           0        284  ...               0   
2             2002         486           0        434  ...               0   
3             1970         216           0        540  ...               0   
4             2000         655           0        490  ...               0   
...            ...         ...         ...        ...  ...             ...   
1452          2000           0           0        953  ...               0   
1453          1988         790         163        589  ...               0   
1454          2006         275           0        877  ...               0   
1455          1996          49        1029          0  ...               0   
1456          1965         830         290        136  ...               0   

      SaleType_New  SaleType_Oth  SaleType_WD  SaleCondition_Abnorml  \
0                0             0            1                      0   
1                0             0            1                      0   
2                0             0            1                      0   
3                0             0            1                      1   
4                0             0            1                      0   
...            ...           ...          ...                    ...   
1452             0             0            1                      0   
1453             0             0            1                      0   
1454             0             0            1                      0   
1455             0             0            1                      0   
1456             0             0            1                      0   

      SaleCondition_AdjLand  SaleCondition_Alloca  SaleCondition_Family  \
0                         0                     0                     0   
1                         0                     0                     0   
2                         0                     0                     0   
3                         0                     0                     0   
4                         0                     0                     0   
...                     ...                   ...                   ...   
1452                      0                     0                     0   
1453                      0                     0                     0   
1454                      0                     0                     0   
1455                      0                     0                     0   
1456                      0                     0                     0   

      SaleCondition_Normal  SaleCondition_Partial  
0                        1                      0  
1                        1                      0  
2                        1                      0  
3                        0                      0  
4                        1                      0  
...                    ...                    ...  
1452                     1                      0  
1453                    

In [8]:
labels

0       12.247694
1       12.109011
2       12.317167
3       11.849398
4       12.429216
          ...    
1452    12.072541
1453    12.254863
1454    12.493130
1455    11.864462
1456    11.901583
Name: SalePrice, Length: 1457, dtype: float64

In [9]:
X_train, X_test, y_train, y_test = train_test_split(Features, labels, test_size=0.20, random_state=42)

In [10]:
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso
from sklearn.linear_model import Ridge
from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import SGDRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_squared_error
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression

In [11]:
rid = Ridge(alpha=.5)
rid.fit(X_train, y_train)
rid.score(X_test,y_test)

0.9155637717965449

In [12]:
rid_predict = rid.predict(X_test)


In [13]:
rid_predict.shape

(292,)

In [14]:
y_test.shape

(292,)

In [15]:
sgd_reg = SGDRegressor(max_iter=100, penalty=None, eta0=0.001)
sgd_reg.fit(X_test, y_test)
sgd_reg.score(X_test,y_test)


-7.009766450393898e+32

In [16]:
sgd_reg.intercept_, sgd_reg.coef_

(array([66979315.81614126]),
 array([ 1.72785739e+11, -2.04096105e+12, -9.23426543e+11, -7.15745880e+09,
         3.35567672e+09, -2.19868617e+11,  1.87092656e+10, -9.31480509e+11,
        -1.02433159e+11,  7.06747577e+11, -3.25950818e+10,  1.56893065e+12,
         7.48151902e+11, -1.15344221e+12,  1.39711938e+09,  3.08445462e+09,
        -1.95933775e+09,  3.09667001e+09, -5.98625071e+09,  1.96847298e+10,
        -3.95998930e+08,  3.83270615e+10, -4.75982746e+09,  6.09265222e+09,
         6.51116460e+11, -2.84943589e+12,  1.56257370e+12,  3.26994349e+11,
        -4.31275042e+11, -2.96365545e+11, -2.41718551e+11,  2.90570992e+11,
         1.49443263e+10,  1.21818730e+11, -5.42538562e+09,  7.25796538e+08,
         2.65750600e+09,  7.06731381e+08,  3.94674169e+09, -7.96979629e+09,
         0.00000000e+00,  6.69793158e+07, -4.55073345e+09,  9.77085886e+08,
         0.00000000e+00,  3.64062688e+09,  1.97924733e+09, -1.79344459e+09,
        -1.54140201e+09,  1.42257859e+09,  6.69793158e+07, 

In [17]:
lasso = Lasso(alpha = 0.1, normalize = True)
lasso.fit(X_train,y_train)
lasso_predict = lasso.predict(X_test)
lasso.score(X_test,y_test)


-0.0022584121551618708

In [18]:
lasso_predict

array([12.02003815, 12.02003815, 12.02003815, 12.02003815, 12.02003815,
       12.02003815, 12.02003815, 12.02003815, 12.02003815, 12.02003815,
       12.02003815, 12.02003815, 12.02003815, 12.02003815, 12.02003815,
       12.02003815, 12.02003815, 12.02003815, 12.02003815, 12.02003815,
       12.02003815, 12.02003815, 12.02003815, 12.02003815, 12.02003815,
       12.02003815, 12.02003815, 12.02003815, 12.02003815, 12.02003815,
       12.02003815, 12.02003815, 12.02003815, 12.02003815, 12.02003815,
       12.02003815, 12.02003815, 12.02003815, 12.02003815, 12.02003815,
       12.02003815, 12.02003815, 12.02003815, 12.02003815, 12.02003815,
       12.02003815, 12.02003815, 12.02003815, 12.02003815, 12.02003815,
       12.02003815, 12.02003815, 12.02003815, 12.02003815, 12.02003815,
       12.02003815, 12.02003815, 12.02003815, 12.02003815, 12.02003815,
       12.02003815, 12.02003815, 12.02003815, 12.02003815, 12.02003815,
       12.02003815, 12.02003815, 12.02003815, 12.02003815, 12.02