In [22]:
import numpy as np
import keras

In [23]:
model = keras.Sequential([keras.layers.Dense(units =1, input_shape = [1])])

In [24]:
model.compile(optimizer="sgd", loss = "mean_squared_error")

In [25]:
x = np.array([-1, 0, 1,2,3], dtype = float)

In [26]:
y = np.array([-3, -1, 1, 3, 5], dtype = float)
# relationship is y = 2x-1

In [27]:
model.fit(x,y,epochs = 10)
# 10 epochs

Epoch 1/10
5/5 [==============================] - 0s 29ms/step - loss: 1.2341
Epoch 2/10
5/5 [==============================] - 0s 192us/step - loss: 1.1657
Epoch 3/10
5/5 [==============================] - 0s 400us/step - loss: 1.1041
Epoch 4/10
5/5 [==============================] - 0s 207us/step - loss: 1.0485
Epoch 5/10
5/5 [==============================] - 0s 191us/step - loss: 0.9981
Epoch 6/10
5/5 [==============================] - 0s 199us/step - loss: 0.9523
Epoch 7/10
5/5 [==============================] - 0s 200us/step - loss: 0.9106
Epoch 8/10
5/5 [==============================] - 0s 399us/step - loss: 0.8724
Epoch 9/10
5/5 [==============================] - 0s 206us/step - loss: 0.8373
Epoch 10/10
5/5 [==============================] - 0s 200us/step - loss: 0.8050


In [28]:
model.predict([110, 10, 0])
# predicted o/p so for from actual

array([[ 1.5798399e+02],
       [ 1.4306161e+01],
       [-6.1622109e-02]], dtype=float32)

In [29]:
model.fit(x,y,epochs = 100)
# with 100 expochs

Epoch 1/100
5/5 [==============================] - 0s 200us/step - loss: 0.7752
Epoch 2/100
5/5 [==============================] - 0s 401us/step - loss: 0.7475
Epoch 3/100
5/5 [==============================] - 0s 200us/step - loss: 0.7217
Epoch 4/100
5/5 [==============================] - 0s 199us/step - loss: 0.6976
Epoch 5/100
5/5 [==============================] - 0s 111us/step - loss: 0.6751
Epoch 6/100
5/5 [==============================] - 0s 201us/step - loss: 0.6539
Epoch 7/100
5/5 [==============================] - 0s 201us/step - loss: 0.6339
Epoch 8/100
5/5 [==============================] - 0s 201us/step - loss: 0.6150
Epoch 9/100
5/5 [==============================] - 0s 199us/step - loss: 0.5971
Epoch 10/100
5/5 [==============================] - 0s 199us/step - loss: 0.5801
Epoch 11/100
5/5 [==============================] - 0s 199us/step - loss: 0.5639
Epoch 12/100
5/5 [==============================] - 0s 401us/step - loss: 0.5484
Epoch 13/100
5/5 [===================

In [30]:
model.predict([110, 10, 0])
#given better almost 90+%

array([[205.27078  ],
       [ 18.031631 ],
       [ -0.6922832]], dtype=float32)

In [31]:
model.fit(x,y,epochs = 500)

Epoch 1/500
5/5 [==============================] - 0s 201us/step - loss: 0.0650
Epoch 2/500
5/5 [==============================] - 0s 200us/step - loss: 0.0635
Epoch 3/500
5/5 [==============================] - 0s 306us/step - loss: 0.0620
Epoch 4/500
5/5 [==============================] - 0s 310us/step - loss: 0.0606
Epoch 5/500
5/5 [==============================] - 0s 199us/step - loss: 0.0592
Epoch 6/500
5/5 [==============================] - 0s 199us/step - loss: 0.0578
Epoch 7/500
5/5 [==============================] - 0s 192us/step - loss: 0.0564
Epoch 8/500
5/5 [==============================] - 0s 201us/step - loss: 0.0551
Epoch 9/500
5/5 [==============================] - 0s 200us/step - loss: 0.0538
Epoch 10/500
5/5 [==============================] - 0s 199us/step - loss: 0.0526
Epoch 11/500
5/5 [==============================] - 0s 0us/step - loss: 0.0514
Epoch 12/500
5/5 [==============================] - 0s 200us/step - loss: 0.0502
Epoch 13/500
5/5 [=====================

Epoch 103/500
5/5 [==============================] - 0s 200us/step - loss: 0.0059
Epoch 104/500
5/5 [==============================] - 0s 201us/step - loss: 0.0057
Epoch 105/500
5/5 [==============================] - 0s 200us/step - loss: 0.0056
Epoch 106/500
5/5 [==============================] - 0s 200us/step - loss: 0.0055
Epoch 107/500
5/5 [==============================] - 0s 200us/step - loss: 0.0053
Epoch 108/500
5/5 [==============================] - 0s 200us/step - loss: 0.0052
Epoch 109/500
5/5 [==============================] - 0s 200us/step - loss: 0.0051
Epoch 110/500
5/5 [==============================] - 0s 200us/step - loss: 0.0050
Epoch 111/500
5/5 [==============================] - 0s 102us/step - loss: 0.0049
Epoch 112/500
5/5 [==============================] - 0s 200us/step - loss: 0.0048
Epoch 113/500
5/5 [==============================] - 0s 400us/step - loss: 0.0046
Epoch 114/500
5/5 [==============================] - 0s 400us/step - loss: 0.0045
Epoch 115/500
5/

Epoch 203/500
5/5 [==============================] - 0s 200us/step - loss: 5.5620e-04
Epoch 204/500
5/5 [==============================] - 0s 200us/step - loss: 5.4324e-04
Epoch 205/500
5/5 [==============================] - 0s 200us/step - loss: 5.3059e-04
Epoch 206/500
5/5 [==============================] - 0s 200us/step - loss: 5.1823e-04
Epoch 207/500
5/5 [==============================] - 0s 200us/step - loss: 5.0616e-04
Epoch 208/500
5/5 [==============================] - 0s 200us/step - loss: 4.9437e-04
Epoch 209/500
5/5 [==============================] - 0s 200us/step - loss: 4.8286e-04
Epoch 210/500
5/5 [==============================] - 0s 200us/step - loss: 4.7160e-04
Epoch 211/500
5/5 [==============================] - 0s 200us/step - loss: 4.6062e-04
Epoch 212/500
5/5 [==============================] - 0s 200us/step - loss: 4.4989e-04
Epoch 213/500
5/5 [==============================] - 0s 200us/step - loss: 4.3941e-04
Epoch 214/500
5/5 [==============================] - 0

Epoch 299/500
5/5 [==============================] - 0s 200us/step - loss: 5.7883e-05
Epoch 300/500
5/5 [==============================] - 0s 199us/step - loss: 5.6536e-05
Epoch 301/500
5/5 [==============================] - 0s 200us/step - loss: 5.5218e-05
Epoch 302/500
5/5 [==============================] - 0s 199us/step - loss: 5.3932e-05
Epoch 303/500
5/5 [==============================] - 0s 200us/step - loss: 5.2676e-05
Epoch 304/500
5/5 [==============================] - 0s 200us/step - loss: 5.1449e-05
Epoch 305/500
5/5 [==============================] - 0s 200us/step - loss: 5.0251e-05
Epoch 306/500
5/5 [==============================] - 0s 199us/step - loss: 4.9080e-05
Epoch 307/500
5/5 [==============================] - 0s 200us/step - loss: 4.7938e-05
Epoch 308/500
5/5 [==============================] - 0s 400us/step - loss: 4.6821e-05
Epoch 309/500
5/5 [==============================] - 0s 200us/step - loss: 4.5730e-05
Epoch 310/500
5/5 [==============================] - 0

Epoch 395/500
5/5 [==============================] - 0s 397us/step - loss: 6.0241e-06
Epoch 396/500
5/5 [==============================] - 0s 399us/step - loss: 5.8839e-06
Epoch 397/500
5/5 [==============================] - 0s 201us/step - loss: 5.7465e-06
Epoch 398/500
5/5 [==============================] - 0s 0us/step - loss: 5.6128e-06
Epoch 399/500
5/5 [==============================] - 0s 200us/step - loss: 5.4818e-06
Epoch 400/500
5/5 [==============================] - 0s 200us/step - loss: 5.3542e-06
Epoch 401/500
5/5 [==============================] - 0s 200us/step - loss: 5.2295e-06
Epoch 402/500
5/5 [==============================] - 0s 199us/step - loss: 5.1076e-06
Epoch 403/500
5/5 [==============================] - 0s 201us/step - loss: 4.9885e-06
Epoch 404/500
5/5 [==============================] - 0s 199us/step - loss: 4.8725e-06
Epoch 405/500
5/5 [==============================] - 0s 201us/step - loss: 4.7590e-06
Epoch 406/500
5/5 [==============================] - 0s 

Epoch 491/500
5/5 [==============================] - 0s 200us/step - loss: 6.2666e-07
Epoch 492/500
5/5 [==============================] - 0s 200us/step - loss: 6.1214e-07
Epoch 493/500
5/5 [==============================] - 0s 0us/step - loss: 5.9779e-07
Epoch 494/500
5/5 [==============================] - 0s 202us/step - loss: 5.8388e-07
Epoch 495/500
5/5 [==============================] - 0s 201us/step - loss: 5.7026e-07
Epoch 496/500
5/5 [==============================] - 0s 199us/step - loss: 5.5710e-07
Epoch 497/500
5/5 [==============================] - 0s 199us/step - loss: 5.4406e-07
Epoch 498/500
5/5 [==============================] - 0s 200us/step - loss: 5.3136e-07
Epoch 499/500
5/5 [==============================] - 0s 400us/step - loss: 5.1897e-07
Epoch 500/500
5/5 [==============================] - 0s 403us/step - loss: 5.0699e-07


In [32]:
model.predict([110, 10, 0])
#given better almost 98+%

array([[218.96216   ],
       [ 18.997332  ],
       [ -0.99915063]], dtype=float32)